apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: v413-cnv-fbc-gmzm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v413-cnv-fbc-gmzm
    app.kubernetes.io/part-of: cnv-fbc
  name: v413-cnv-fbc-gmzm
  namespace: cnv-fbc-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: v413-cnv-fbc-gmzm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: v413-cnv-fbc-gmzm
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:GPveg-v413-cnv-fbc-gmzm
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 50051
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 50051
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
