apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: v413-cnv-fbc-gmzm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v413-cnv-fbc-gmzm
    app.kubernetes.io/part-of: cnv-fbc
  name: v413-cnv-fbc-gmzm
  namespace: cnv-fbc-tenant
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: v413-cnv-fbc-gmzm
status:
  loadBalancer: {}
